import type { Metadata } from "next";
import Header from "@/components/Header";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ProtectedLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col min-h-screen">
      <div className="hidden md:inline-block h-[94px] border-b w-full sticky top-0">
        <Header />
      </div>

      <div className="flex flex-col-reverse sm:flex-row relative h-[calc(100vh-94px)]">
        <div className="border-t sm:border-t-0 sm:border-r sticky top-0 bottom-0 lg:w-full lg:max-w-[250px] flex-shrink-0 flex flex-col">
          <Navbar />
        </div>
        <main className="flex-1 overflow-y-auto">{children}</main>
      </div>
    </div>
  );
}
